version: "2"
services:
  namenode:
    container_name: namenode
    image: apache/hadoop:3
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
      - 9000:9000
    env_file:
      - ../config/.env
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
    networks:
      hadoop:
        ipv4_address: 192.168.100.2

  resourcemanager:
    container_name: resourcemanager
    image: apache/hadoop:3
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    env_file:
      - ../config/.env
    volumes:
      - ./test.sh:/opt/test.sh
    networks:
      hadoop:
        ipv4_address: 192.168.100.3

networks:
  hadoop:
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
